insert into LOST_ITEM(LOST_ID ,FOUND_PLACE ,LOST_DESC, LOST_ITEM_NAME ,NAME, PHONE_NUMBER) 
values(1,'road','Canteen','Purse','Reshma','9087638904');
insert into LOST_ITEM(LOST_ID ,FOUND_PLACE ,LOST_DESC, LOST_ITEM_NAME ,NAME, PHONE_NUMBER) 
values(2,'road','ID card','id card','Reshma','9087612345');
insert into LOST_ITEM(LOST_ID ,FOUND_PLACE ,LOST_DESC, LOST_ITEM_NAME ,NAME, PHONE_NUMBER) 
values(3,'road','ID card','id card','Reshma','9087612345');
insert into LOST_ITEM(LOST_ID ,FOUND_PLACE ,LOST_DESC, LOST_ITEM_NAME ,NAME, PHONE_NUMBER) 
values(4,'road','ID card','id card','Reshma','9087612345');


insert into Employee(EMP_ID ,EMP_NAME ,EMP_SALARY) 
values(100,'RESHMA','10000');
insert into Employee(EMP_ID ,EMP_NAME ,EMP_SALARY) 
values(200,'SHRINIVAS','20000');



insert into Address(ADDRESS_ID ,ADDRESS_DISTRICT ,ADDRESS_STATE,PINCODE,EMPLOYEE_ID) 
values(800,'BENGALURU','KARNATAKA',576102,100);
insert into Address(ADDRESS_ID ,ADDRESS_DISTRICT ,ADDRESS_STATE,PINCODE,EMPLOYEE_ID) 
values(801,'UDUPI','KARNATAKA',576102,200);
insert into Address(ADDRESS_ID ,ADDRESS_DISTRICT ,ADDRESS_STATE,PINCODE,EMPLOYEE_ID) 
values(802,'MANGLORE','KARNATAKA',576102,100);
insert into Address(ADDRESS_ID ,ADDRESS_DISTRICT ,ADDRESS_STATE,PINCODE,EMPLOYEE_ID) 
values(803,'COCHIN','KERALA',590102,100);


insert into PASSPORT(PASSPORT_ID ,PASSPORT_CITIZEN ) 
values(1234,'INDIAN');
insert into PASSPORT(PASSPORT_ID ,PASSPORT_CITIZEN ) 
values(1994,'AUSTRALIAN');

insert into STUDENT(STU_ID ,STU_NAME ,PASSPORT_ID) 
values(100,'RESHMA',1234);
insert into STUDENT(STU_ID ,STU_NAME ,PASSPORT_ID) 
values(101,'RESHMA B',1994);





















